import 'package:ar_chem_lab/presentation/periodic_table/element_model.dart';
import 'package:flutter/material.dart';

class ElementData {
  static const Map<String, Color> categoryColors = {
    'diatomic nonmetal': Color(0xFF2A4165), // Blue
    'noble gas': Color(0xFF6D414B), // Maroon
    'alkali metal': Color(0xFF244D57), // Dark Teal
    'alkaline earth metal': Color(0xFF622E39), // Brown
    'metalloid': Color(0xFF613B28), // Dark Brown
    'polyatomic nonmetal': Color(0xFF3F51B5), // Indigo
    'post-transition metal': Color(0xFF2F4D47), // Dark Teal
    'transition metal': Color(0xFF433C65), // Violet
    'lanthanide': Color(0xFF004A77), // Dark Blue
    'actinide': Color(0xFF613B28), // Dark Brown
    'unknown': Color(0xFF46474C), // Dark Grey
  };

  static Color getColor(String category) {
    return categoryColors[category] ?? Colors.grey;
  }

  static List<ElementModel> get allElements => [
    ElementModel(
      atomicNumber: 1,
      symbol: "H",
      name: "Hydrogen",
      atomicMass: "1.008",
      category: "diatomic nonmetal",
      electronicConfiguration: "1s1",
      x: 1,
      y: 1,
      block: "s",
      summary:
          "Hydrogen is a chemical element with symbol H and atomic number 1. With a standard atomic weight of 1.008, hydrogen is the lightest element on the periodic table.",
      color: getColor('diatomic nonmetal'),
    ),
    ElementModel(
      atomicNumber: 2,
      symbol: "He",
      name: "Helium",
      atomicMass: "4.0026",
      category: "noble gas",
      electronicConfiguration: "[He]",
      x: 18,
      y: 1,
      block: "s",
      summary:
          "Helium is a chemical element with symbol He and atomic number 2. It is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas, the first in the noble gas group in the periodic table.",
      color: getColor('noble gas'),
    ),
    ElementModel(
      atomicNumber: 3,
      symbol: "Li",
      name: "Lithium",
      atomicMass: "6.94",
      category: "alkali metal",
      electronicConfiguration: "[He] 2s1",
      x: 1,
      y: 2,
      block: "s",
      summary:
          "Lithium is a chemical element with symbol Li and atomic number 3. It is a soft, silvery-white alkali metal. Under standard conditions, it is the lightest metal and the lightest solid element.",
      color: getColor('alkali metal'),
    ),
    ElementModel(
      atomicNumber: 4,
      symbol: "Be",
      name: "Beryllium",
      atomicMass: "9.0122",
      category: "alkaline earth metal",
      electronicConfiguration: "[He] 2s2",
      x: 2,
      y: 2,
      block: "s",
      summary:
          "Beryllium is a chemical element with symbol Be and atomic number 4. It is a relatively rare element in the universe, usually occurring as a product of the spallation of larger atomic nuclei that have collided with cosmic rays.",
      color: getColor('alkaline earth metal'),
    ),
    ElementModel(
      atomicNumber: 5,
      symbol: "B",
      name: "Boron",
      atomicMass: "10.81",
      category: "metalloid",
      electronicConfiguration: "[He] 2s2 2p1",
      x: 13,
      y: 2,
      block: "p",
      summary:
          "Boron is a chemical element with symbol B and atomic number 5. Because boron is produced entirely by cosmic ray spallation and not by stellar nucleosynthesis, it is a low-abundance element in the Solar system and in the Earth's crust.",
      color: getColor('metalloid'),
    ),
    ElementModel(
      atomicNumber: 6,
      symbol: "C",
      name: "Carbon",
      atomicMass: "12.011",
      category: "polyatomic nonmetal",
      electronicConfiguration: "[He] 2s2 2p2",
      x: 14,
      y: 2,
      block: "p",
      summary:
          "Carbon is a chemical element with symbol C and atomic number 6. It is nonmetallic and tetravalent—making four electrons available to form covalent chemical bonds.",
      color: getColor('polyatomic nonmetal'),
    ),
    ElementModel(
      atomicNumber: 7,
      symbol: "N",
      name: "Nitrogen",
      atomicMass: "14.007",
      category: "diatomic nonmetal",
      electronicConfiguration: "[He] 2s2 2p3",
      x: 15,
      y: 2,
      block: "p",
      summary:
          "Nitrogen is a chemical element with symbol N and atomic number 7. It was first discovered and isolated by Scottish physician Daniel Rutherford in 1772.",
      color: getColor('diatomic nonmetal'),
    ),
    ElementModel(
      atomicNumber: 8,
      symbol: "O",
      name: "Oxygen",
      atomicMass: "15.999",
      category: "diatomic nonmetal",
      electronicConfiguration: "[He] 2s2 2p4",
      x: 16,
      y: 2,
      block: "p",
      summary:
          "Oxygen is a chemical element with symbol O and atomic number 8. It is a member of the chalcogen group on the periodic table, a highly reactive nonmetal, and an oxidizing agent that readily forms oxides with most elements as well as with other compounds.",
      color: getColor('diatomic nonmetal'),
    ),
    ElementModel(
      atomicNumber: 9,
      symbol: "F",
      name: "Fluorine",
      atomicMass: "18.998",
      category: "diatomic nonmetal",
      electronicConfiguration: "[He] 2s2 2p5",
      x: 17,
      y: 2,
      block: "p",
      summary:
          "Fluorine is a chemical element with symbol F and atomic number 9. It is the lightest halogen and exists as a highly toxic pale yellow diatomic gas at standard conditions.",
      color: getColor('diatomic nonmetal'),
    ),
    ElementModel(
      atomicNumber: 10,
      symbol: "Ne",
      name: "Neon",
      atomicMass: "20.180",
      category: "noble gas",
      electronicConfiguration: "[He] 2s2 2p6",
      x: 18,
      y: 2,
      block: "p",
      summary:
          "Neon is a chemical element with symbol Ne and atomic number 10. It is a noble gas. Neon is a colorless, odorless, inert monatomic gas under standard conditions, with about two-thirds the density of air.",
      color: getColor('noble gas'),
    ),
    ElementModel(
      atomicNumber: 11,
      symbol: "Na",
      name: "Sodium",
      atomicMass: "22.990",
      category: "alkali metal",
      electronicConfiguration: "[Ne] 3s1",
      x: 1,
      y: 3,
      block: "s",
      summary:
          "Sodium is a chemical element with symbol Na and atomic number 11. It is a soft, silvery-white, highly reactive metal.",
      color: getColor('alkali metal'),
    ),
    ElementModel(
      atomicNumber: 12,
      symbol: "Mg",
      name: "Magnesium",
      atomicMass: "24.305",
      category: "alkaline earth metal",
      electronicConfiguration: "[Ne] 3s2",
      x: 2,
      y: 3,
      block: "s",
      summary:
          "Magnesium is a chemical element with symbol Mg and atomic number 12. It is a shiny gray solid which bears a close physical resemblance to the other five elements in the second column (group 2, or alkaline earth metals) of the periodic table.",
      color: getColor('alkaline earth metal'),
    ),
    ElementModel(
      atomicNumber: 13,
      symbol: "Al",
      name: "Aluminium",
      atomicMass: "26.982",
      category: "post-transition metal",
      electronicConfiguration: "[Ne] 3s2 3p1",
      x: 13,
      y: 3,
      block: "p",
      summary:
          "Aluminium (or aluminum; see spelling differences) is a chemical element in the boron group with symbol Al and atomic number 13. It is a silvery-white, soft, nonmagnetic, ductile metal.",
      color: getColor('post-transition metal'),
    ),
    ElementModel(
      atomicNumber: 14,
      symbol: "Si",
      name: "Silicon",
      atomicMass: "28.085",
      category: "metalloid",
      electronicConfiguration: "[Ne] 3s2 3p2",
      x: 14,
      y: 3,
      block: "p",
      summary:
          "Silicon is a chemical element with symbol Si and atomic number 14. Less reactive than its chemical analog carbon, the nonmetal is tetravalent in all stable compounds.",
      color: getColor('metalloid'),
    ),
    ElementModel(
      atomicNumber: 15,
      symbol: "P",
      name: "Phosphorus",
      atomicMass: "30.974",
      category: "polyatomic nonmetal",
      electronicConfiguration: "[Ne] 3s2 3p3",
      x: 15,
      y: 3,
      block: "p",
      summary:
          "Phosphorus is a chemical element with symbol P and atomic number 15. Elemental phosphorus exists in two major forms, white phosphorus and red phosphorus, but because it is highly reactive, phosphorus is never found as a free element on Earth.",
      color: getColor('polyatomic nonmetal'),
    ),
    ElementModel(
      atomicNumber: 16,
      symbol: "S",
      name: "Sulfur",
      atomicMass: "32.06",
      category: "polyatomic nonmetal",
      electronicConfiguration: "[Ne] 3s2 3p4",
      x: 16,
      y: 3,
      block: "p",
      summary:
          "Sulfur or sulphur is a chemical element with symbol S and atomic number 16. It is an abundant, multivalent and nonmetallic.",
      color: getColor('polyatomic nonmetal'),
    ),
    ElementModel(
      atomicNumber: 17,
      symbol: "Cl",
      name: "Chlorine",
      atomicMass: "35.45",
      category: "diatomic nonmetal",
      electronicConfiguration: "[Ne] 3s2 3p5",
      x: 17,
      y: 3,
      block: "p",
      summary:
          "Chlorine is a chemical element with symbol Cl and atomic number 17. The second-lightest of the halogens, it appears between fluorine and bromine in the periodic table and its properties are mostly intermediate between them.",
      color: getColor('diatomic nonmetal'),
    ),
    ElementModel(
      atomicNumber: 18,
      symbol: "Ar",
      name: "Argon",
      atomicMass: "39.948",
      category: "noble gas",
      electronicConfiguration: "[Ne] 3s2 3p6",
      x: 18,
      y: 3,
      block: "p",
      summary:
          "Argon is a chemical element with symbol Ar and atomic number 18. It is in the noble gas group of the periodic table. Argon is the third-most abundant gas in the Earth's atmosphere, at 0.934% (9340 ppmv).",
      color: getColor('noble gas'),
    ),
    ElementModel(
      atomicNumber: 19,
      symbol: "K",
      name: "Potassium",
      atomicMass: "39.098",
      category: "alkali metal",
      electronicConfiguration: "[Ar] 4s1",
      x: 1,
      y: 4,
      block: "s",
      summary:
          "Potassium is a chemical element with symbol K and atomic number 19. It was first isolated from potash, the ashes of plants, from which its name derives.",
      color: getColor('alkali metal'),
    ),
    ElementModel(
      atomicNumber: 20,
      symbol: "Ca",
      name: "Calcium",
      atomicMass: "40.078",
      category: "alkaline earth metal",
      electronicConfiguration: "[Ar] 4s2",
      x: 2,
      y: 4,
      block: "s",
      summary:
          "Calcium is a chemical element with symbol Ca and atomic number 20. Calcium is a soft gray alkaline earth metal, fifth-most-abundant element by mass in the Earth's crust.",
      color: getColor('alkaline earth metal'),
    ),
    ElementModel(
      atomicNumber: 21,
      symbol: "Sc",
      name: "Scandium",
      atomicMass: "44.956",
      category: "transition metal",
      electronicConfiguration: "[Ar] 3d1 4s2",
      x: 3,
      y: 4,
      block: "d",
      summary:
          "Scandium is a chemical element with symbol Sc and atomic number 21. A silvery-white metallic d-block element, it has historically been classified as a rare-earth element, together with yttrium and the lanthanides.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 22,
      symbol: "Ti",
      name: "Titanium",
      atomicMass: "47.867",
      category: "transition metal",
      electronicConfiguration: "[Ar] 3d2 4s2",
      x: 4,
      y: 4,
      block: "d",
      summary:
          "Titanium is a chemical element with symbol Ti and atomic number 22. It is a lustrous transition metal with a silver color, low density, and high strength.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 23,
      symbol: "V",
      name: "Vanadium",
      atomicMass: "50.942",
      category: "transition metal",
      electronicConfiguration: "[Ar] 3d3 4s2",
      x: 5,
      y: 4,
      block: "d",
      summary:
          "Vanadium is a chemical element with symbol V and atomic number 23. It is a hard, silvery-grey, ductile, malleable transition metal.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 24,
      symbol: "Cr",
      name: "Chromium",
      atomicMass: "51.996",
      category: "transition metal",
      electronicConfiguration: "[Ar] 3d5 4s1",
      x: 6,
      y: 4,
      block: "d",
      summary:
          "Chromium is a chemical element with symbol Cr and atomic number 24. It is the first element in group 6.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 25,
      symbol: "Mn",
      name: "Manganese",
      atomicMass: "54.938",
      category: "transition metal",
      electronicConfiguration: "[Ar] 3d5 4s2",
      x: 7,
      y: 4,
      block: "d",
      summary:
          "Manganese is a chemical element with symbol Mn and atomic number 25. It is not found as a free element in nature; it is often found in minerals in combination with iron.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 26,
      symbol: "Fe",
      name: "Iron",
      atomicMass: "55.845",
      category: "transition metal",
      electronicConfiguration: "[Ar] 3d6 4s2",
      x: 8,
      y: 4,
      block: "d",
      summary:
          "Iron is a chemical element with symbol Fe (from Latin: ferrum) and atomic number 26. It is a metal that belongs to the first transition series and group 8 of the periodic table.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 27,
      symbol: "Co",
      name: "Cobalt",
      atomicMass: "58.933",
      category: "transition metal",
      electronicConfiguration: "[Ar] 3d7 4s2",
      x: 9,
      y: 4,
      block: "d",
      summary:
          "Cobalt is a chemical element with symbol Co and atomic number 27. Like nickel, cobalt is found in the Earth's crust only in chemically combined form, save for small deposits found in alloys of natural meteoric iron.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 28,
      symbol: "Ni",
      name: "Nickel",
      atomicMass: "58.693",
      category: "transition metal",
      electronicConfiguration: "[Ar] 3d8 4s2",
      x: 10,
      y: 4,
      block: "d",
      summary:
          "Nickel is a chemical element with symbol Ni and atomic number 28. It is a silvery-white lustrous metal with a slight golden tinge.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 29,
      symbol: "Cu",
      name: "Copper",
      atomicMass: "63.546",
      category: "transition metal",
      electronicConfiguration: "[Ar] 3d10 4s1",
      x: 11,
      y: 4,
      block: "d",
      summary:
          "Copper is a chemical element with symbol Cu (from Latin: cuprum) and atomic number 29. It is a soft, malleable, and ductile metal with very high thermal and electrical conductivity.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 30,
      symbol: "Zn",
      name: "Zinc",
      atomicMass: "65.38",
      category: "transition metal",
      electronicConfiguration: "[Ar] 3d10 4s2",
      x: 12,
      y: 4,
      block: "d",
      summary:
          "Zinc is a chemical element with symbol Zn and atomic number 30. It is the first element in group 12 of the periodic table.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 31,
      symbol: "Ga",
      name: "Gallium",
      atomicMass: "69.723",
      category: "post-transition metal",
      electronicConfiguration: "[Ar] 3d10 4s2 4p1",
      x: 13,
      y: 4,
      block: "p",
      summary:
          "Gallium is a chemical element with symbol Ga and atomic number 31. It is in the boron group.",
      color: getColor('post-transition metal'),
    ),
    ElementModel(
      atomicNumber: 32,
      symbol: "Ge",
      name: "Germanium",
      atomicMass: "72.630",
      category: "metalloid",
      electronicConfiguration: "[Ar] 3d10 4s2 4p2",
      x: 14,
      y: 4,
      block: "p",
      summary:
          "Germanium is a chemical element with symbol Ge and atomic number 32. It is a lustrous, hard-brittle, grayish-white metalloid in the carbon group, chemically similar to its group neighbors silicon and tin.",
      color: getColor('metalloid'),
    ),
    ElementModel(
      atomicNumber: 33,
      symbol: "As",
      name: "Arsenic",
      atomicMass: "74.922",
      category: "metalloid",
      electronicConfiguration: "[Ar] 3d10 4s2 4p3",
      x: 15,
      y: 4,
      block: "p",
      summary:
          "Arsenic is a chemical element with symbol As and atomic number 33. Arsenic occurs in many minerals, usually in combination with sulfur and metals, but also as a pure elemental crystal.",
      color: getColor('metalloid'),
    ),
    ElementModel(
      atomicNumber: 34,
      symbol: "Se",
      name: "Selenium",
      atomicMass: "78.971",
      category: "polyatomic nonmetal",
      electronicConfiguration: "[Ar] 3d10 4s2 4p4",
      x: 16,
      y: 4,
      block: "p",
      summary:
          "Selenium is a chemical element with symbol Se and atomic number 34. It is a nonmetal with properties that are intermediate between the elements above and below in the periodic table, sulfur and tellurium.",
      color: getColor('polyatomic nonmetal'),
    ),
    ElementModel(
      atomicNumber: 35,
      symbol: "Br",
      name: "Bromine",
      atomicMass: "79.904",
      category: "diatomic nonmetal",
      electronicConfiguration: "[Ar] 3d10 4s2 4p5",
      x: 17,
      y: 4,
      block: "p",
      summary:
          "Bromine is a chemical element with symbol Br and atomic number 35. It is the third-lightest halogen, and is a fuming red-brown liquid at room temperature that evaporates readily to form a similar-coloured gas.",
      color: getColor('diatomic nonmetal'),
    ),
    ElementModel(
      atomicNumber: 36,
      symbol: "Kr",
      name: "Krypton",
      atomicMass: "83.798",
      category: "noble gas",
      electronicConfiguration: "[Ar] 3d10 4s2 4p6",
      x: 18,
      y: 4,
      block: "p",
      summary:
          "Krypton is a chemical element with symbol Kr and atomic number 36. It is a member of group 18 (noble gases) elements.",
      color: getColor('noble gas'),
    ),
    ElementModel(
      atomicNumber: 37,
      symbol: "Rb",
      name: "Rubidium",
      atomicMass: "85.468",
      category: "alkali metal",
      electronicConfiguration: "[Kr] 5s1",
      x: 1,
      y: 5,
      block: "s",
      summary:
          "Rubidium is a chemical element with symbol Rb and atomic number 37. Rubidium is a soft, silvery-white metallic element of the alkali metal group.",
      color: getColor('alkali metal'),
    ),
    ElementModel(
      atomicNumber: 38,
      symbol: "Sr",
      name: "Strontium",
      atomicMass: "87.62",
      category: "alkaline earth metal",
      electronicConfiguration: "[Kr] 5s2",
      x: 2,
      y: 5,
      block: "s",
      summary:
          "Strontium is a chemical element with symbol Sr and atomic number 38. An alkaline earth metal, strontium is a soft silver-white yellowish metallic element that is highly chemically reactive.",
      color: getColor('alkaline earth metal'),
    ),
    ElementModel(
      atomicNumber: 39,
      symbol: "Y",
      name: "Yttrium",
      atomicMass: "88.906",
      category: "transition metal",
      electronicConfiguration: "[Kr] 4d1 5s2",
      x: 3,
      y: 5,
      block: "d",
      summary:
          "Yttrium is a chemical element with symbol Y and atomic number 39. It is a silvery-metallic transition metal chemically similar to the lanthanides and has often been classified as a \"rare-earth element\".",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 40,
      symbol: "Zr",
      name: "Zirconium",
      atomicMass: "91.224",
      category: "transition metal",
      electronicConfiguration: "[Kr] 4d2 5s2",
      x: 4,
      y: 5,
      block: "d",
      summary:
          "Zirconium is a chemical element with symbol Zr and atomic number 40. The name zirconium is taken from the name of the mineral zircon, the most important source of zirconium.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 41,
      symbol: "Nb",
      name: "Niobium",
      atomicMass: "92.906",
      category: "transition metal",
      electronicConfiguration: "[Kr] 4d4 5s1",
      x: 5,
      y: 5,
      block: "d",
      summary:
          "Niobium, formerly columbium, is a chemical element with symbol Nb (formerly Cb) and atomic number 41. It is a soft, grey, crystalline, ductile transition metal.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 42,
      symbol: "Mo",
      name: "Molybdenum",
      atomicMass: "95.95",
      category: "transition metal",
      electronicConfiguration: "[Kr] 4d5 5s1",
      x: 6,
      y: 5,
      block: "d",
      summary:
          "Molybdenum is a chemical element with symbol Mo and atomic number 42. The name is from Neo-Latin molybdaenum, from Ancient Greek Μόλυβδος molybdos, meaning lead.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 43,
      symbol: "Tc",
      name: "Technetium",
      atomicMass: "98",
      category: "transition metal",
      electronicConfiguration: "[Kr] 4d5 5s2",
      x: 7,
      y: 5,
      block: "d",
      summary:
          "Technetium is a chemical element with symbol Tc and atomic number 43. It is the lightest element whose isotopes are all radioactive, none of which is stable other than the fully ionized state of 97Tc.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 44,
      symbol: "Ru",
      name: "Ruthenium",
      atomicMass: "101.07",
      category: "transition metal",
      electronicConfiguration: "[Kr] 4d7 5s1",
      x: 8,
      y: 5,
      block: "d",
      summary:
          "Ruthenium is a chemical element with symbol Ru and atomic number 44. It is a rare transition metal belonging to the platinum group of the periodic table.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 45,
      symbol: "Rh",
      name: "Rhodium",
      atomicMass: "102.91",
      category: "transition metal",
      electronicConfiguration: "[Kr] 4d8 5s1",
      x: 9,
      y: 5,
      block: "d",
      summary:
          "Rhodium is a chemical element with symbol Rh and atomic number 45. It is a rare, silvery-white, hard, and chemically inert transition metal.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 46,
      symbol: "Pd",
      name: "Palladium",
      atomicMass: "106.42",
      category: "transition metal",
      electronicConfiguration: "[Kr] 4d10",
      x: 10,
      y: 5,
      block: "d",
      summary:
          "Palladium is a chemical element with symbol Pd and atomic number 46. It is a rare and lustrous silvery-white metal discovered in 1803 by the English chemist William Hyde Wollaston.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 47,
      symbol: "Ag",
      name: "Silver",
      atomicMass: "107.87",
      category: "transition metal",
      electronicConfiguration: "[Kr] 4d10 5s1",
      x: 11,
      y: 5,
      block: "d",
      summary:
          "Silver is a chemical element with symbol Ag and atomic number 47. A soft, white, lustrous transition metal, it exhibits the highest electrical conductivity, thermal conductivity, and reflectivity of any metal.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 48,
      symbol: "Cd",
      name: "Cadmium",
      atomicMass: "112.41",
      category: "transition metal",
      electronicConfiguration: "[Kr] 4d10 5s2",
      x: 12,
      y: 5,
      block: "d",
      summary:
          "Cadmium is a chemical element with symbol Cd and atomic number 48. This soft, bluish-white metal is chemically similar to the two other stable metals in group 12, zinc and mercury.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 49,
      symbol: "In",
      name: "Indium",
      atomicMass: "114.82",
      category: "post-transition metal",
      electronicConfiguration: "[Kr] 4d10 5s2 5p1",
      x: 13,
      y: 5,
      block: "p",
      summary:
          "Indium is a chemical element with symbol In and atomic number 49. It is a post-transition metal that is more alkali than gallium and less alkali than thallium.",
      color: getColor('post-transition metal'),
    ),
    ElementModel(
      atomicNumber: 50,
      symbol: "Sn",
      name: "Tin",
      atomicMass: "118.71",
      category: "post-transition metal",
      electronicConfiguration: "[Kr] 4d10 5s2 5p2",
      x: 14,
      y: 5,
      block: "p",
      summary:
          "Tin is a chemical element with the symbol Sn (from Latin: stannum) and atomic number 50. It is a main group metal in group 14 of the periodic table.",
      color: getColor('post-transition metal'),
    ),
    ElementModel(
      atomicNumber: 51,
      symbol: "Sb",
      name: "Antimony",
      atomicMass: "121.76",
      category: "metalloid",
      electronicConfiguration: "[Kr] 4d10 5s2 5p3",
      x: 15,
      y: 5,
      block: "p",
      summary:
          "Antimony is a chemical element with symbol Sb (from Latin: stibium) and atomic number 51. A lustrous gray metalloid, it is found in nature mainly as the sulfide mineral stibnite (Sb2S3).",
      color: getColor('metalloid'),
    ),
    ElementModel(
      atomicNumber: 52,
      symbol: "Te",
      name: "Tellurium",
      atomicMass: "127.60",
      category: "metalloid",
      electronicConfiguration: "[Kr] 4d10 5s2 5p4",
      x: 16,
      y: 5,
      block: "p",
      summary:
          "Tellurium is a chemical element with symbol Te and atomic number 52. It is a brittle, mildly toxic, rare, silver-white metalloid.",
      color: getColor('metalloid'),
    ),
    ElementModel(
      atomicNumber: 53,
      symbol: "I",
      name: "Iodine",
      atomicMass: "126.90",
      category: "diatomic nonmetal",
      electronicConfiguration: "[Kr] 4d10 5s2 5p5",
      x: 17,
      y: 5,
      block: "p",
      summary:
          "Iodine is a chemical element with symbol I and atomic number 53. The heaviest of the stable halogens, it exists as a lustrous, purple-black non-metallic solid at standard conditions.",
      color: getColor('diatomic nonmetal'),
    ),
    ElementModel(
      atomicNumber: 54,
      symbol: "Xe",
      name: "Xenon",
      atomicMass: "131.29",
      category: "noble gas",
      electronicConfiguration: "[Kr] 4d10 5s2 5p6",
      x: 18,
      y: 5,
      block: "p",
      summary:
          "Xenon is a chemical element with symbol Xe and atomic number 54. It is a colorless, dense, odorless noble gas found in the Earth's atmosphere in trace amounts.",
      color: getColor('noble gas'),
    ),
    ElementModel(
      atomicNumber: 55,
      symbol: "Cs",
      name: "Cesium",
      atomicMass: "132.91",
      category: "alkali metal",
      electronicConfiguration: "[Xe] 6s1",
      x: 1,
      y: 6,
      block: "s",
      summary:
          "Cesium is a chemical element with symbol Cs and atomic number 55. It is a soft, silvery-gold alkali metal with a melting point of 28.5 °C (83.3 °F), which makes it one of only five elemental metals that are liquid at or near room temperature.",
      color: getColor('alkali metal'),
    ),
    ElementModel(
      atomicNumber: 56,
      symbol: "Ba",
      name: "Barium",
      atomicMass: "137.33",
      category: "alkaline earth metal",
      electronicConfiguration: "[Xe] 6s2",
      x: 2,
      y: 6,
      block: "s",
      summary:
          "Barium is a chemical element with symbol Ba and atomic number 56. It is the fifth element in group 2 and is a soft, silvery alkaline earth metal.",
      color: getColor('alkaline earth metal'),
    ),
    ElementModel(
      atomicNumber: 57,
      symbol: "La",
      name: "Lanthanum",
      atomicMass: "138.91",
      category: "lanthanide",
      electronicConfiguration: "[Xe] 5d1 6s2",
      x: 3,
      y: 9,
      block: "f",
      summary:
          "Lanthanum is a chemical element with symbol La and atomic number 57. It is a soft, ductile, silvery-white metal that tarnishes rapidly when exposed to air.",
      color: getColor('lanthanide'),
    ),
    ElementModel(
      atomicNumber: 58,
      symbol: "Ce",
      name: "Cerium",
      atomicMass: "140.12",
      category: "lanthanide",
      electronicConfiguration: "[Xe] 4f1 5d1 6s2",
      x: 4,
      y: 9,
      block: "f",
      summary:
          "Cerium is a chemical element with symbol Ce and atomic number 58. Cerium is a soft, ductile, and silvery-white metal that tarnishes when exposed to air.",
      color: getColor('lanthanide'),
    ),
    ElementModel(
      atomicNumber: 59,
      symbol: "Pr",
      name: "Praseodymium",
      atomicMass: "140.91",
      category: "lanthanide",
      electronicConfiguration: "[Xe] 4f3 6s2",
      x: 5,
      y: 9,
      block: "f",
      summary:
          "Praseodymium is a chemical element with symbol Pr and atomic number 59. Praseodymium is a soft, silvery, malleable and ductile metal in the lanthanide group.",
      color: getColor('lanthanide'),
    ),
    ElementModel(
      atomicNumber: 60,
      symbol: "Nd",
      name: "Neodymium",
      atomicMass: "144.24",
      category: "lanthanide",
      electronicConfiguration: "[Xe] 4f4 6s2",
      x: 6,
      y: 9,
      block: "f",
      summary:
          "Neodymium is a chemical element with symbol Nd and atomic number 60. Neodymium is a soft, silvery metal that tarnishes in air.",
      color: getColor('lanthanide'),
    ),
    ElementModel(
      atomicNumber: 61,
      symbol: "Pm",
      name: "Promethium",
      atomicMass: "145",
      category: "lanthanide",
      electronicConfiguration: "[Xe] 4f5 6s2",
      x: 7,
      y: 9,
      block: "f",
      summary:
          "Promethium is a chemical element with symbol Pm and atomic number 61. All of its isotopes are radioactive; it is extremely rare, with only about 500-600 grams naturally occurring in Earth's crust at any given time.",
      color: getColor('lanthanide'),
    ),
    ElementModel(
      atomicNumber: 62,
      symbol: "Sm",
      name: "Samarium",
      atomicMass: "150.36",
      category: "lanthanide",
      electronicConfiguration: "[Xe] 4f6 6s2",
      x: 8,
      y: 9,
      block: "f",
      summary:
          "Samarium is a chemical element with symbol Sm and atomic number 62. It is a moderately hard silvery metal that readily oxidizes in air.",
      color: getColor('lanthanide'),
    ),
    ElementModel(
      atomicNumber: 63,
      symbol: "Eu",
      name: "Europium",
      atomicMass: "151.96",
      category: "lanthanide",
      electronicConfiguration: "[Xe] 4f7 6s2",
      x: 9,
      y: 9,
      block: "f",
      summary:
          "Europium is a chemical element with symbol Eu and atomic number 63. It was isolated in 1901 and is named after the continent of Europe.",
      color: getColor('lanthanide'),
    ),
    ElementModel(
      atomicNumber: 64,
      symbol: "Gd",
      name: "Gadolinium",
      atomicMass: "157.25",
      category: "lanthanide",
      electronicConfiguration: "[Xe] 4f7 5d1 6s2",
      x: 10,
      y: 9,
      block: "f",
      summary:
          "Gadolinium is a chemical element with symbol Gd and atomic number 64. Gadolinium is a silvery-white metal when oxidation is removed.",
      color: getColor('lanthanide'),
    ),
    ElementModel(
      atomicNumber: 65,
      symbol: "Tb",
      name: "Terbium",
      atomicMass: "158.93",
      category: "lanthanide",
      electronicConfiguration: "[Xe] 4f9 6s2",
      x: 11,
      y: 9,
      block: "f",
      summary:
          "Terbium is a chemical element with symbol Tb and atomic number 65. It is a silvery-white, rare earth metal that is malleable, ductile, and soft enough to be cut with a knife.",
      color: getColor('lanthanide'),
    ),
    ElementModel(
      atomicNumber: 66,
      symbol: "Dy",
      name: "Dysprosium",
      atomicMass: "162.50",
      category: "lanthanide",
      electronicConfiguration: "[Xe] 4f10 6s2",
      x: 12,
      y: 9,
      block: "f",
      summary:
          "Dysprosium is a chemical element with symbol Dy and atomic number 66. It is a rare earth element with a metallic silver luster.",
      color: getColor('lanthanide'),
    ),
    ElementModel(
      atomicNumber: 67,
      symbol: "Ho",
      name: "Holmium",
      atomicMass: "164.93",
      category: "lanthanide",
      electronicConfiguration: "[Xe] 4f11 6s2",
      x: 13,
      y: 9,
      block: "f",
      summary:
          "Holmium is a chemical element with symbol Ho and atomic number 67. Part of the lanthanide series, holmium is a rare earth element.",
      color: getColor('lanthanide'),
    ),
    ElementModel(
      atomicNumber: 68,
      symbol: "Er",
      name: "Erbium",
      atomicMass: "167.26",
      category: "lanthanide",
      electronicConfiguration: "[Xe] 4f12 6s2",
      x: 14,
      y: 9,
      block: "f",
      summary:
          "Erbium is a chemical element with symbol Er and atomic number 68. A silvery-white solid metal when artificially isolated, natural erbium is always found in chemical combination with other elements.",
      color: getColor('lanthanide'),
    ),
    ElementModel(
      atomicNumber: 69,
      symbol: "Tm",
      name: "Thulium",
      atomicMass: "168.93",
      category: "lanthanide",
      electronicConfiguration: "[Xe] 4f13 6s2",
      x: 15,
      y: 9,
      block: "f",
      summary:
          "Thulium is a chemical element with symbol Tm and atomic number 69. It is the thirteenth and third-last element in the lanthanide series.",
      color: getColor('lanthanide'),
    ),
    ElementModel(
      atomicNumber: 70,
      symbol: "Yb",
      name: "Ytterbium",
      atomicMass: "173.05",
      category: "lanthanide",
      electronicConfiguration: "[Xe] 4f14 6s2",
      x: 16,
      y: 9,
      block: "f",
      summary:
          "Ytterbium is a chemical element with symbol Yb and atomic number 70. It is the fourteenth and penultimate element in the lanthanide series, which is the basis of the relative stability of its +2 oxidation state.",
      color: getColor('lanthanide'),
    ),
    ElementModel(
      atomicNumber: 71,
      symbol: "Lu",
      name: "Lutetium",
      atomicMass: "174.97",
      category: "lanthanide",
      electronicConfiguration: "[Xe] 4f14 5d1 6s2",
      x: 17,
      y: 9,
      block: "d",
      summary:
          "Lutetium is a chemical element with symbol Lu and atomic number 71. It is the last element in the lanthanide series, and arguably the first element of the 6th-period transition metals.",
      color: getColor('lanthanide'),
    ),
    ElementModel(
      atomicNumber: 72,
      symbol: "Hf",
      name: "Hafnium",
      atomicMass: "178.49",
      category: "transition metal",
      electronicConfiguration: "[Xe] 4f14 5d2 6s2",
      x: 4,
      y: 6,
      block: "d",
      summary:
          "Hafnium is a chemical element with symbol Hf and atomic number 72. A lustrous, silvery gray, tetravalent transition metal, hafnium chemically resembles zirconium and is found in many zirconium minerals.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 73,
      symbol: "Ta",
      name: "Tantalum",
      atomicMass: "180.95",
      category: "transition metal",
      electronicConfiguration: "[Xe] 4f14 5d3 6s2",
      x: 5,
      y: 6,
      block: "d",
      summary:
          "Tantalum is a chemical element with symbol Ta and atomic number 73. Previously known as tantalium, it is named after Tantalus, a villain from Greek mythology.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 74,
      symbol: "W",
      name: "Tungsten",
      atomicMass: "183.84",
      category: "transition metal",
      electronicConfiguration: "[Xe] 4f14 5d4 6s2",
      x: 6,
      y: 6,
      block: "d",
      summary:
          "Tungsten is a chemical element with symbol W and atomic number 74. The name tungsten comes from the former Swedish name for the tungstate mineral scheelite, tungh sten, meaning \"heavy stone\".",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 75,
      symbol: "Re",
      name: "Rhenium",
      atomicMass: "186.21",
      category: "transition metal",
      electronicConfiguration: "[Xe] 4f14 5d5 6s2",
      x: 7,
      y: 6,
      block: "d",
      summary:
          "Rhenium is a chemical element with symbol Re and atomic number 75. It is a silvery-white, heavy, third-row transition metal in group 7 of the periodic table.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 76,
      symbol: "Os",
      name: "Osmium",
      atomicMass: "190.23",
      category: "transition metal",
      electronicConfiguration: "[Xe] 4f14 5d6 6s2",
      x: 8,
      y: 6,
      block: "d",
      summary:
          "Osmium is a chemical element with symbol Os and atomic number 76. It is a hard, brittle, bluish-white transition metal in the platinum group that is found as a trace element in alloys, mostly in platinum ores.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 77,
      symbol: "Ir",
      name: "Iridium",
      atomicMass: "192.22",
      category: "transition metal",
      electronicConfiguration: "[Xe] 4f14 5d7 6s2",
      x: 9,
      y: 6,
      block: "d",
      summary:
          "Iridium is a chemical element with symbol Ir and atomic number 77. A very hard, brittle, silvery-white transition metal of the platinum group, iridium is considered to be the second-densest element.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 78,
      symbol: "Pt",
      name: "Platinum",
      atomicMass: "195.08",
      category: "transition metal",
      electronicConfiguration: "[Xe] 4f14 5d9 6s1",
      x: 10,
      y: 6,
      block: "d",
      summary:
          "Platinum is a chemical element with symbol Pt and atomic number 78. It is a dense, malleable, ductile, highly unreactive, precious, silver-white transition metal.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 79,
      symbol: "Au",
      name: "Gold",
      atomicMass: "196.97",
      category: "transition metal",
      electronicConfiguration: "[Xe] 4f14 5d10 6s1",
      x: 11,
      y: 6,
      block: "d",
      summary:
          "Gold is a chemical element with symbol Au and atomic number 79. In its purest form, it is a bright, slightly reddish yellow, dense, soft, malleable, and ductile metal.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 80,
      symbol: "Hg",
      name: "Mercury",
      atomicMass: "200.59",
      category: "transition metal",
      electronicConfiguration: "[Xe] 4f14 5d10 6s2",
      x: 12,
      y: 6,
      block: "d",
      summary:
          "Mercury is a chemical element with symbol Hg and atomic number 80. It is commonly known as quicksilver and was formerly named hydrargyrum.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 81,
      symbol: "Tl",
      name: "Thallium",
      atomicMass: "204.38",
      category: "post-transition metal",
      electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p1",
      x: 13,
      y: 6,
      block: "p",
      summary:
          "Thallium is a chemical element with symbol Tl and atomic number 81. This soft gray post-transition metal is not found free in nature.",
      color: getColor('post-transition metal'),
    ),
    ElementModel(
      atomicNumber: 82,
      symbol: "Pb",
      name: "Lead",
      atomicMass: "207.2",
      category: "post-transition metal",
      electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p2",
      x: 14,
      y: 6,
      block: "p",
      summary:
          "Lead is a chemical element with symbol Pb and atomic number 82. It is a heavy metal that is denser than most common materials.",
      color: getColor('post-transition metal'),
    ),
    ElementModel(
      atomicNumber: 83,
      symbol: "Bi",
      name: "Bismuth",
      atomicMass: "208.98",
      category: "post-transition metal",
      electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p3",
      x: 15,
      y: 6,
      block: "p",
      summary:
          "Bismuth is a chemical element with symbol Bi and atomic number 83. Bismuth, a pentavalent post-transition metal and one of the pnictogens, chemically resembles its lighter homologs arsenic and antimony.",
      color: getColor('post-transition metal'),
    ),
    ElementModel(
      atomicNumber: 84,
      symbol: "Po",
      name: "Polonium",
      atomicMass: "209",
      category: "post-transition metal",
      electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p4",
      x: 16,
      y: 6,
      block: "p",
      summary:
          "Polonium is a chemical element with symbol Po and atomic number 84. A rare and highly radioactive metal with no stable isotopes, polonium is chemically similar to selenium and tellurium.",
      color: getColor('post-transition metal'),
    ),
    ElementModel(
      atomicNumber: 85,
      symbol: "At",
      name: "Astatine",
      atomicMass: "210",
      category: "metalloid",
      electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p5",
      x: 17,
      y: 6,
      block: "p",
      summary:
          "Astatine is a chemical element with symbol At and atomic number 85. It is the rarest naturally occurring element in the Earth's crust.",
      color: getColor('metalloid'),
    ),
    ElementModel(
      atomicNumber: 86,
      symbol: "Rn",
      name: "Radon",
      atomicMass: "222",
      category: "noble gas",
      electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p6",
      x: 18,
      y: 6,
      block: "p",
      summary:
          "Radon is a chemical element with symbol Rn and atomic number 86. It is a radioactive, colorless, odorless, tasteless noble gas.",
      color: getColor('noble gas'),
    ),
    ElementModel(
      atomicNumber: 87,
      symbol: "Fr",
      name: "Francium",
      atomicMass: "223",
      category: "alkali metal",
      electronicConfiguration: "[Rn] 7s1",
      x: 1,
      y: 7,
      block: "s",
      summary:
          "Francium is a chemical element with symbol Fr and atomic number 87. It is extremely radioactive.",
      color: getColor('alkali metal'),
    ),
    ElementModel(
      atomicNumber: 88,
      symbol: "Ra",
      name: "Radium",
      atomicMass: "226",
      category: "alkaline earth metal",
      electronicConfiguration: "[Rn] 7s2",
      x: 2,
      y: 7,
      block: "s",
      summary:
          "Radium is a chemical element with symbol Ra and atomic number 88. It is the sixth element in group 2 of the periodic table, also known as the alkaline earth metals.",
      color: getColor('alkaline earth metal'),
    ),
    ElementModel(
      atomicNumber: 89,
      symbol: "Ac",
      name: "Actinium",
      atomicMass: "227",
      category: "actinide",
      electronicConfiguration: "[Rn] 6d1 7s2",
      x: 3,
      y: 10,
      block: "f",
      summary:
          "Actinium is a chemical element with symbol Ac and atomic number 89. It was discovered in 1899 by French chemist André-Louis Debierne.",
      color: getColor('actinide'),
    ),
    ElementModel(
      atomicNumber: 90,
      symbol: "Th",
      name: "Thorium",
      atomicMass: "232.04",
      category: "actinide",
      electronicConfiguration: "[Rn] 6d2 7s2",
      x: 4,
      y: 10,
      block: "f",
      summary:
          "Thorium is a chemical element with symbol Th and atomic number 90. A radioactive actinide metal, thorium is one of only two significantly radioactive elements that still occur naturally in large quantities as a primordial element.",
      color: getColor('actinide'),
    ),
    ElementModel(
      atomicNumber: 91,
      symbol: "Pa",
      name: "Protactinium",
      atomicMass: "231.04",
      category: "actinide",
      electronicConfiguration: "[Rn] 5f2 6d1 7s2",
      x: 5,
      y: 10,
      block: "f",
      summary:
          "Protactinium is a chemical element with symbol Pa and atomic number 91. It is a dense, silvery-gray actinide metal which readily reacts with oxygen, water vapor and inorganic acids.",
      color: getColor('actinide'),
    ),
    ElementModel(
      atomicNumber: 92,
      symbol: "U",
      name: "Uranium",
      atomicMass: "238.03",
      category: "actinide",
      electronicConfiguration: "[Rn] 5f3 6d1 7s2",
      x: 6,
      y: 10,
      block: "f",
      summary:
          "Uranium is a chemical element with symbol U and atomic number 92. It is a silvery-grey metal in the actinide series of the periodic table.",
      color: getColor('actinide'),
    ),
    ElementModel(
      atomicNumber: 93,
      symbol: "Np",
      name: "Neptunium",
      atomicMass: "237",
      category: "actinide",
      electronicConfiguration: "[Rn] 5f4 6d1 7s2",
      x: 7,
      y: 10,
      block: "f",
      summary:
          "Neptunium is a chemical element with symbol Np and atomic number 93. A radioactive actinide metal, neptunium is the first transuranic element.",
      color: getColor('actinide'),
    ),
    ElementModel(
      atomicNumber: 94,
      symbol: "Pu",
      name: "Plutonium",
      atomicMass: "244",
      category: "actinide",
      electronicConfiguration: "[Rn] 5f6 7s2",
      x: 8,
      y: 10,
      block: "f",
      summary:
          "Plutonium is a chemical element with symbol Pu and atomic number 94. It is an actinide metal of silvery-gray appearance that tarnishes when exposed to air, and forms a dull coating when oxidized.",
      color: getColor('actinide'),
    ),
    ElementModel(
      atomicNumber: 95,
      symbol: "Am",
      name: "Americium",
      atomicMass: "243",
      category: "actinide",
      electronicConfiguration: "[Rn] 5f7 7s2",
      x: 9,
      y: 10,
      block: "f",
      summary:
          "Americium is a chemical element with symbol Am and atomic number 95. It is a radioactive transuranic element in the actinide series.",
      color: getColor('actinide'),
    ),
    ElementModel(
      atomicNumber: 96,
      symbol: "Cm",
      name: "Curium",
      atomicMass: "247",
      category: "actinide",
      electronicConfiguration: "[Rn] 5f7 6d1 7s2",
      x: 10,
      y: 10,
      block: "f",
      summary:
          "Curium is a chemical element with symbol Cm and atomic number 96. It is a radioactive transuranic element in the actinide series.",
      color: getColor('actinide'),
    ),
    ElementModel(
      atomicNumber: 97,
      symbol: "Bk",
      name: "Berkelium",
      atomicMass: "247",
      category: "actinide",
      electronicConfiguration: "[Rn] 5f9 7s2",
      x: 11,
      y: 10,
      block: "f",
      summary:
          "Berkelium is a chemical element with symbol Bk and atomic number 97. It is a member of the actinide and transuranium element series.",
      color: getColor('actinide'),
    ),
    ElementModel(
      atomicNumber: 98,
      symbol: "Cf",
      name: "Californium",
      atomicMass: "251",
      category: "actinide",
      electronicConfiguration: "[Rn] 5f10 7s2",
      x: 12,
      y: 10,
      block: "f",
      summary:
          "Californium is a chemical element with symbol Cf and atomic number 98. The element was first synthesized in 1950 at the University of California Radiation Laboratory in Berkeley.",
      color: getColor('actinide'),
    ),
    ElementModel(
      atomicNumber: 99,
      symbol: "Es",
      name: "Einsteinium",
      atomicMass: "252",
      category: "actinide",
      electronicConfiguration: "[Rn] 5f11 7s2",
      x: 13,
      y: 10,
      block: "f",
      summary:
          "Einsteinium is a chemical element with symbol Es and atomic number 99. It is the seventh transuranic element, and an actinide.",
      color: getColor('actinide'),
    ),
    ElementModel(
      atomicNumber: 100,
      symbol: "Fm",
      name: "Fermium",
      atomicMass: "257",
      category: "actinide",
      electronicConfiguration: "[Rn] 5f12 7s2",
      x: 14,
      y: 10,
      block: "f",
      summary:
          "Fermium is a chemical element with symbol Fm and atomic number 100. It is an actinide and the heaviest element that can be formed by neutron bombardment of lighter elements.",
      color: getColor('actinide'),
    ),
    ElementModel(
      atomicNumber: 101,
      symbol: "Md",
      name: "Mendelevium",
      atomicMass: "258",
      category: "actinide",
      electronicConfiguration: "[Rn] 5f13 7s2",
      x: 15,
      y: 10,
      block: "f",
      summary:
          "Mendelevium is a chemical element with symbol Md and atomic number 101. A metallic radioactive transuranium element in the actinide series, it is the first element that currently cannot be produced in macroscopic quantities through neutron bombardment of lighter elements.",
      color: getColor('actinide'),
    ),
    ElementModel(
      atomicNumber: 102,
      symbol: "No",
      name: "Nobelium",
      atomicMass: "259",
      category: "actinide",
      electronicConfiguration: "[Rn] 5f14 7s2",
      x: 16,
      y: 10,
      block: "f",
      summary:
          "Nobelium is a chemical element with symbol No and atomic number 102. It is named in honor of Alfred Nobel, the inventor of dynamite and benefactor of science.",
      color: getColor('actinide'),
    ),
    ElementModel(
      atomicNumber: 103,
      symbol: "Lr",
      name: "Lawrencium",
      atomicMass: "262",
      category: "actinide",
      electronicConfiguration: "[Rn] 5f14 6d1 7s2",
      x: 17,
      y: 10,
      block: "d",
      summary:
          "Lawrencium is a chemical element with symbol Lr and atomic number 103. It is named in honor of Ernest Lawrence, inventor of the cyclotron.",
      color: getColor('actinide'),
    ),
    ElementModel(
      atomicNumber: 104,
      symbol: "Rf",
      name: "Rutherfordium",
      atomicMass: "267",
      category: "transition metal",
      electronicConfiguration: "[Rn] 5f14 6d2 7s2",
      x: 4,
      y: 7,
      block: "d",
      summary:
          "Rutherfordium is a chemical element with symbol Rf and atomic number 104. It is named after physicist Ernest Rutherford.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 105,
      symbol: "Db",
      name: "Dubnium",
      atomicMass: "268",
      category: "transition metal",
      electronicConfiguration: "[Rn] 5f14 6d3 7s2",
      x: 5,
      y: 7,
      block: "d",
      summary:
          "Dubnium is a chemical element with symbol Db and atomic number 105. It is named after the town of Dubna in Russia.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 106,
      symbol: "Sg",
      name: "Seaborgium",
      atomicMass: "271",
      category: "transition metal",
      electronicConfiguration: "[Rn] 5f14 6d4 7s2",
      x: 6,
      y: 7,
      block: "d",
      summary:
          "Seaborgium is a chemical element with symbol Sg and atomic number 106. It is named after the American nuclear chemist Glenn T. Seaborg.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 107,
      symbol: "Bh",
      name: "Bohrium",
      atomicMass: "272",
      category: "transition metal",
      electronicConfiguration: "[Rn] 5f14 6d5 7s2",
      x: 7,
      y: 7,
      block: "d",
      summary:
          "Bohrium is a chemical element with symbol Bh and atomic number 107. It is named after Danish physicist Niels Bohr.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 108,
      symbol: "Hs",
      name: "Hassium",
      atomicMass: "270",
      category: "transition metal",
      electronicConfiguration: "[Rn] 5f14 6d6 7s2",
      x: 8,
      y: 7,
      block: "d",
      summary:
          "Hassium is a chemical element with symbol Hs and atomic number 108. It is named after the German state of Hesse.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 109,
      symbol: "Mt",
      name: "Meitnerium",
      atomicMass: "276",
      category: "unknown",
      electronicConfiguration: "[Rn] 5f14 6d7 7s2",
      x: 9,
      y: 7,
      block: "d",
      summary:
          "Meitnerium is a chemical element with symbol Mt and atomic number 109. It is named after Austrian physicist Lise Meitner.",
      color: getColor('unknown'),
    ),
    ElementModel(
      atomicNumber: 110,
      symbol: "Ds",
      name: "Darmstadtium",
      atomicMass: "281",
      category: "unknown",
      electronicConfiguration: "[Rn] 5f14 6d9 7s1",
      x: 10,
      y: 7,
      block: "d",
      summary:
          "Darmstadtium is a chemical element with symbol Ds and atomic number 110. It is named after the city of Darmstadt, Germany.",
      color: getColor('unknown'),
    ),
    ElementModel(
      atomicNumber: 111,
      symbol: "Rg",
      name: "Roentgenium",
      atomicMass: "280",
      category: "unknown",
      electronicConfiguration: "[Rn] 5f14 6d10 7s1",
      x: 11,
      y: 7,
      block: "d",
      summary:
          "Roentgenium is a chemical element with symbol Rg and atomic number 111. It is named after Wilhelm Röntgen, the discoverer of X-rays.",
      color: getColor('unknown'),
    ),
    ElementModel(
      atomicNumber: 112,
      symbol: "Cn",
      name: "Copernicium",
      atomicMass: "285",
      category: "transition metal",
      electronicConfiguration: "[Rn] 5f14 6d10 7s2",
      x: 12,
      y: 7,
      block: "d",
      summary:
          "Copernicium is a chemical element with symbol Cn and atomic number 112. It is named after the astronomer Nicolaus Copernicus.",
      color: getColor('transition metal'),
    ),
    ElementModel(
      atomicNumber: 113,
      symbol: "Nh",
      name: "Nihonium",
      atomicMass: "284",
      category: "unknown",
      electronicConfiguration: "[Rn] 5f14 6d10 7s2 7p1",
      x: 13,
      y: 7,
      block: "p",
      summary:
          "Nihonium is a chemical element with symbol Nh and atomic number 113. It is named after the common Japanese name for Japan (Nihon).",
      color: getColor('unknown'),
    ),
    ElementModel(
      atomicNumber: 114,
      symbol: "Fl",
      name: "Flerovium",
      atomicMass: "289",
      category: "post-transition metal",
      electronicConfiguration: "[Rn] 5f14 6d10 7s2 7p2",
      x: 14,
      y: 7,
      block: "p",
      summary:
          "Flerovium is a chemical element with symbol Fl and atomic number 114. It is named after the Flerov Laboratory of Nuclear Reactions.",
      color: getColor('post-transition metal'),
    ),
    ElementModel(
      atomicNumber: 115,
      symbol: "Mc",
      name: "Moscovium",
      atomicMass: "288",
      category: "unknown",
      electronicConfiguration: "[Rn] 5f14 6d10 7s2 7p3",
      x: 15,
      y: 7,
      block: "p",
      summary:
          "Moscovium is a chemical element with symbol Mc and atomic number 115. It is named after the Moscow Oblast, where the research center is located.",
      color: getColor('unknown'),
    ),
    ElementModel(
      atomicNumber: 116,
      symbol: "Lv",
      name: "Livermorium",
      atomicMass: "293",
      category: "unknown",
      electronicConfiguration: "[Rn] 5f14 6d10 7s2 7p4",
      x: 16,
      y: 7,
      block: "p",
      summary:
          "Livermorium is a chemical element with symbol Lv and atomic number 116. It is named after the Lawrence Livermore National Laboratory.",
      color: getColor('unknown'),
    ),
    ElementModel(
      atomicNumber: 117,
      symbol: "Ts",
      name: "Tennessine",
      atomicMass: "294",
      category: "unknown",
      electronicConfiguration: "[Rn] 5f14 6d10 7s2 7p5",
      x: 17,
      y: 7,
      block: "p",
      summary:
          "Tennessine is a chemical element with symbol Ts and atomic number 117. It is named after the state of Tennessee.",
      color: getColor('unknown'),
    ),
    ElementModel(
      atomicNumber: 118,
      symbol: "Og",
      name: "Oganesson",
      atomicMass: "294",
      category: "unknown",
      electronicConfiguration: "[Rn] 5f14 6d10 7s2 7p6",
      x: 18,
      y: 7,
      block: "p",
      summary:
          "Oganesson is a chemical element with symbol Og and atomic number 118. It is named after Yuri Oganessian.",
      color: getColor('unknown'),
    ),
  ];
}
